# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af1df15bc4c8f2bd794f70bb418ee2144b15f4b3bf990a5e2ed9ef49d6ddc266cccdf963c294f37616b4a02cf5a42d3f445524b1e6c2ba8d60bba6ca1efe8d16

test:
  secret_key_base: 356fd0697e05647d8cbe75dc0eed0a5e204d3d39c102872202e28e74063516122dedb05f2d7f9cc36cd224ad20672b3e8b0b99a83f6241df8abe926c1d0b2301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
